name: Auto Tag

on:
  push:
    branches:
      - master  # Change this if you're using a different main branch (e.g., "main")

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to get all tags

      - name: Get Latest Tag
        id: get_latest_tag
        run: echo "TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo v0.0.0)" >> $GITHUB_ENV

      - name: Calculate Next Tag
        id: next_tag
        run: |
          latest_tag=${{ env.TAG }}
          echo "Latest tag: $latest_tag"

          # Extract version numbers
          major=$(echo $latest_tag | cut -d'.' -f1 | sed 's/v//')
          minor=$(echo $latest_tag | cut -d'.' -f2)
          patch=$(echo $latest_tag | cut -d'.' -f3)

          # Increment patch version
          new_patch=$((patch + 1))
          new_tag="v$major.$minor.$new_patch"
          echo "New tag: $new_tag"

          echo "NEW_TAG=$new_tag" >> $GITHUB_ENV

      - name: Set Git Config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create and Push Tag
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # Ensure the token is passed from the secrets
        run: |
          git tag ${{ env.NEW_TAG }}
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git ${{ env.NEW_TAG }}
