name: Semantic Release

on:
  workflow_run:
    workflows: ["Java CI"]
    branches: [ master ]
    types: [ completed ]

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup semantic-release
        run: |
          npm install -g semantic-release @semantic-release/git @semantic-release/changelog

      - name: Determine next version
        id: semantic
        run: |
          npx semantic-release
          echo "NEW_VERSION=$(npx semantic-release | grep 'The next release version is' | sed 's/.*is //')" >> $GITHUB_ENV

      - name: Update version in build.properties
        if: env.NEW_VERSION != ''
        run: |
          ant update-version -Dnew.version=${{ env.NEW_VERSION }}

      - name: Update version in build.xml
        if: env.NEW_VERSION != ''
        run: |
          sed -i "s/<property name=\"version\" value=\".*\"\/>/<property name=\"version\" value=\"$NEW_VERSION\"\/>/g" build.xml

      - name: Build release artifacts
        run: ant -noinput -buildfile build.xml release

      - name: Release
        if: env.NEW_VERSION != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release